version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: laravel-redis

    nginx:
      image: nginx:alpine
      container_name: laravel-nginx
      working_dir: /home
      volumes:
          - D:\고니랩\source\popup-manager:/home/laravel
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    php-fpm:
      build: php-fpm
      container_name: laravel-php-fpm
      working_dir: /home
      volumes:
        - D:\고니랩\source\popup-manager:/home/laravel
        - ./php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
        - ./php-fpm/php.ini:/etc/php.ini
