version: "3.1"
services:

    nginx:
      image: nginx:alpine
      container_name: butlerlounge-nginx
      working_dir: /home
      volumes:
          - D:\source\butlerlounge:/home
          - ./nginx/butlerlounge.conf:/etc/nginx/conf.d/butlerlounge.conf
          - ./nginx/admin-butlerlounge.conf:/etc/nginx/conf.d/admin-butlerlounge.conf
          - ./nginx/admin-butlerlounge-dina.conf:/etc/nginx/conf.d/admin-butlerlounge-dina.conf
      ports:
       - "80:80"
       - "8088:8088"
       - "8089:8089"

    php-fpm:
      build: php-fpm
      container_name: butlerlounge-php-fpm
      working_dir: /home
      volumes:
        - D:\source\butlerlounge:/home
        - ./php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
        - ./php-fpm/php.ini:/etc/php.ini
