version: "3.1"
services:

    # redis:
    #   image: redis:alpine
    #   container_name: laravel-redis

    webserver:
      image: nginx:alpine
      container_name: laravel-webserver
      working_dir: /home
      volumes:
          - .:/home
          - ./nginx/www.conf:/etc/nginx/conf.d/www.conf
          - ./nginx/new.conf:/etc/nginx/conf.d/default.conf
          - ./nginx/newadmin.conf:/etc/nginx/conf.d/newadmin.conf
          - ./nginx/www_admin.conf:/etc/nginx/conf.d/www_admin.conf
      ports:
       - "80:80"
       - "8088:8088"
       - "9090:9090"
       - "9088:9088"

    php-fpm:
      build: php-fpm
      container_name: laravel-php-fpm
      working_dir: /home
      volumes:
        - .:/home
        - ./php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
        - ./php-fpm/php.ini:/etc/php.ini
