version: "3.1"
services:

    # redis:
    #   image: redis:alpine
    #   container_name: laravel-redis

    webserver:
      image: nginx:alpine
      container_name: laravel-webserver
      working_dir: /home
      volumes:
          - .:/home
          - ./nginx/www.conf:/etc/nginx/conf.d/www.conf
      ports:
       - "80:80"

    php-fpm:
      build: php-fpm
      container_name: laravel-php-fpm
      working_dir: /home
      volumes:
        - .:/home
        - ./php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
        - ./php-fpm/php.ini:/etc/php.ini
