version: "3"

services:
    database:
      build:
        context: ./mariaDB
        dockerfile: ./mariaDB.Dockerfile
      container_name: mariaDB
      restart: always
      
      environment:
        MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mariadb_secret
        MYSQL_USER: test
        MYSQL_PASSWORD_FILE: /run/secrets/mariadb_secret
        TZ: Asia/Seoul
      secrets:
        - mariadb_secret
      ports:
        - "3306:3306"
      volumes:
        - ./mariaDB/data:/var/lib/mysql
      command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

      networks:
        - mariadb
    
secrets:
  mariadb_secret:
    file: mariadb_secret

networks:
  mariadb:
    name: mariadb