version: "3"

services:
  
    mysql:
      build:
        context: ./mysql
        dockerfile: ./mysql.Dockerfile
      container_name: mysql
      environment:
        MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_secret
        MYSQL_USER: SH91
        MYSQL_PASSWORD_FILE: /run/secrets/mysql_secret
      secrets:
        - mysql_secret
      ports:
        - "3307:3306"
      volumes:
        - ./mysql/data:/var/lib/mysql
      command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

      networks:
        - backend
        - default
  
secrets:
  mysql_secret:
    file: mysql_secret

networks:
  backend:
    name: backend