version: "3.7"
services:
  db_mysql:
    build:
      context: ./mysql
      dockerfile: ./mysql.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_secret
      MYSQL_USER: SH91
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_secret
    secrets:
      - mysql_secret
    ports:
      - "3307:3306"

secrets:
  mysql_secret:
    file: mysql_secret