version: "3.1"
services:

    nginx:
      image: nginx:alpine
      container_name: dina_hotel-nginx
      working_dir: /home
      volumes:
          - D:\source\butlerlounge:/home
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    php-fpm:
      build: php-fpm
      container_name: dina_hotel-php-fpm
      working_dir: /home
      volumes:
        - D:\source\butlerlounge:/home
        - ./php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
        - ./php-fpm/php.ini:/etc/php.ini
