version: "3.1"
services:

    redis:
      image: redis:alpine
      command: redis-server --requirepass 123123 --port 6379
      container_name: redis
      hostname: redis
      labels:
        - "name=redis"
        - "mode=standalone"
      ports:
        - 6379:6379
